module CryptAPI
  CRYPTAPI_HOST: string
  CRYPTAPI_URL: string
  VERSION: String

  class API
    @callback_url: string
    @coin: string
    @own_address: string
    @coin: string
    @parameters: Hash[untyped, untyped]
    @ca_params: Hash[untyped, untyped]
    @api_key: string
    @payment_address: string

    def get_address: -> string

    def get_conversion: -> untyped

    def get_logs: -> untyped

    def get_qrcode: -> untyped

    def get_info: -> untyped

    def self.get_supported_coins: -> untyped

    def self.get_estimate: -> untyped

    def self.create_payout: -> untyped

    def self.list_payouts: -> untyped

    def self.get_payout_wallet: -> untyped

    def self.create_payout_by_ids: -> untyped

    def self.process_payout: -> untyped

    def self.check_payout_status: -> untyped

  end

  private

  def self.process_request_get: -> untyped
  def self.process_request_post: -> untyped
end

class TestCryptAPI
  def test_can_fetch_logs: -> TrueClass

  def test_can_generate_address: -> TrueClass

  def test_can_get_conversion: -> TrueClass

  def test_can_get_estimate: -> TrueClass

  def test_can_get_info: -> TrueClass

  def test_can_get_qrcode: -> TrueClass

  def test_can_get_supported_coins: -> TrueClass

  def test_that_it_has_a_version_number: -> TrueClass
end
